site_name: SimpliPlay Docs
theme:
  name: material
  custom_dir: custom/
  palette:
    scheme: slate  # Light: "default", Dark: "slate"
    primary: blue
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
